[package]
name = "openweather_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.8"
reqwest = { version = "0.12.5", features = ["blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
